#!/bin/bash

rsync -aP ./defaults/ ~/
killall plasmashell
killall dolphin
killall konsole
kstart plasmashell
dolphin . &
sleep 2
kdialog --msgbox "You must logoff and then logon again for the changes to take full effect"
